export enum Notifications {
    prolicenseCopied = "Пролицензия создана по образцу",
    prolicenseCreated = "Пролицензия создана",
    prolicenseChanged = "Пролицензия обновлена",
    prolicensePublished = "Пролицензия опубликована",
    prolicenseUnpublished = "Пролицензия снята с публикации",
    prolicenseDeleted = "Пролицензия удалена",
    draftCreated = `Выполнен переход к заявке в статусе "Черновик"`,
    createdRequest = "Заявка подана",
    createdCritGrp = "Группа создана",
    createdCriteria = "Критерий добавлен",
    changedExperts = "Эксперты группы критериев изменены",
    changedClubWorkers = "Сотрудники клуба для доступа к группе критериев изменены",
    madeDecision = "Решение по документу критерия принято",
    saved = "Сохранено",
    addedDocs = "Документы добавлены",
    licStatusSelected = "Решение по заявке принято",
    reportCreated = "Отчет сформирован",
    roleSaved = "Роль сохранена с выбранными правами",
    roleRightsChanged = "Права изменены",
    userAdded = "Пользователь добавлен",
    userRightsChanged = "Права пользователя изменены",
    userRoleChanged = "Роль пользователя изменена",
    userGrpCritChanged = "Группы критериев пользователя изменены",
    savedLicenseText = "Текст лицензии сохранен",
    commissionCreated = "Заседание добавлено",
    requestsAdded = "Заявки добавлены"
}