name: run integrations tests
on: workflow_dispatch
jobs:
  run_tests:
    runs-on: windows-latest
    steps:
     - name : Setup Node.js environment
       uses: actions/setup-node@v3
       with:
        node-version: 16
     - run: npm install
  
