name: run integrations tests
on: workflow_dispatch
jobs:
  run_tests:
    runs-on: windows-latest
    steps:
     - name : Get repository code
       uses: actions/checkout@v3
     - name : Install dependencies
       run: npm ci
  
